# Generated by Django 5.2.15 on 2026-06-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callerName', models.CharField(max_length=100)),
                ('callerNumber', models.CharField(max_length=20)),
                ('receiverNumber', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('callDirection', models.BooleanField(default=False)),
                ('callStatus', models.BooleanField(default=False)),
                ('callDuration', models.IntegerField()),
                ('callCost', models.FloatField()),
                ('callStartTime', models.DateTimeField()),
                ('callEndTime', models.DateTimeField()),
            ],
            
            options={
                'db_table': 'calls',
                'managed': False,
            },
        ),
    ]
